### ISSUE TITLE
How to get latest release of bloomd rpm at http://vortex-rpm.org?

### ISSUE THREAD

**Issue by puffCN** [vortex-rpm/bloomd#1]
http://vortex-rpm.org/el6/x86_64/repoview/bloomd.html
bloomd-0.5.0-7.vortex.el6.x86_64 [47 KiB]   Changelog by Ilya A. Otyutskiy (2013-02-22)

Latest release is：0.7.4

**Comment by thesharp** [comment]
Hey @puffCN.

I don't have time for that package anymore. Pull requests are always welcome!
